volumes:
  media:
    driver: local
    driver_opts:
      type: nfs
      o: addr=nas.farrow.local,nolock,soft,rw
      device: :/volume1/media

services:
  app:
    container_name: media-org-app
    build:
      target: dev
    volumes:
      - ./app:/app
      - media:/media
    stdin_open: true
    tty: true
