volumes:
  media:
    driver: local
    driver_opts:
      type: nfs
      o: addr=nas.farrow.local,nolock,soft,rw
      device: :/volume1/media

services:
  temp:
    container_name: music-org-temp
    build: .
    volumes:
      - ./app:/app
      - ./cli:/usr/local/bin/cli
      - media:/media
    stdin_open: true
    tty: true
  frontend:
    container_name: music-org-frontend
    build: .
    volumes:
      - ./app:/app
      - ./cli:/usr/local/bin/cli
      - media:/media
    stdin_open: true
    ports:
      - 3333:3000
    tty: true
  server:
    container_name: music-org-server
    build: .
    volumes:
      - ./app:/app
      - ./cli:/usr/local/bin/cli
      - media:/media
    ports:
      - 3334:3000
    stdin_open: true
    tty: true
