volumes:
  media:
    driver: local
    driver_opts:
      type: nfs
      o: addr=nas.farrow.local,nolock,soft,rw
      device: :/volume1/media

services:
  temp:
    container_name: music-org-temp
    build: .
    volumes:
      - ./app:/app
      - ./cli:/usr/local/bin/cli
      - media:/media
    stdin_open: true
    tty: true
  app:
    container_name: music-org-app
    build: .
    volumes:
      - ./app:/app
      - ./cli:/usr/local/bin/cli
      - media:/media
    stdin_open: true
    tty: true
