volumes:
  media:
    driver: local
    driver_opts:
      type: nfs
      o: addr=nas.farrow.local,nolock,soft,rw
      device: :/volume1/media

services:
  temp:
    container_name: music-org-temp
    build:
      target: dist
    volumes:
      # - ./app:/app
      - media:/media
    stdin_open: true
    tty: true
