services:
  temp:
    container_name: music-org-temp
    build: .
    volumes:
      - ./app:/app
      - /mnt/media:/media
    stdin_open: true
    tty: true
  app:
    container_name: music-org-app
    build: .
    volumes:
      - ./app:/app
      - ./.media:/media
    stdin_open: true
    tty: true
