#!/bin/bash



find /media/music/lossless -name "*.m4a" -print0 | while read -d $'\0' file
do
  channels="$(ffprobe -i "$file" -show_streams -select_streams a:0 -hide_banner -loglevel error | grep channels=)"
 
  if [ "$channels" != "channels=2" ]
  then
    echo "$file $channels"
  fi
done